# 光标样式
cursor:
  style: Beam

hide_cursor_when_typing: true

window:
  padding:
    x: 5
    y: 2

# Font configuration 
font:
  normal:
    #family: FiraCode Nerd Font
    family: FiraCode Nerd Font
    style: Regular

  bold:
    #family: Source Code Pro
    family: FiraCode Nerd Font
    style: Bold

  italic:
    family: FiraCode Nerd Font
    style: Italic

  bold_italic:
    family: FiraCode Nerd Font
    style: Bold Italic

  size: 15

# 透明度
background_opacity: 0.88

# Dracula theme
colors:
  # Default colors
  primary:
    background: '#282a36'
    foreground: '#f8f8f2'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#ff5555'
    green:   '#50fa7b'
    yellow:  '#f1fa8c'
    blue:    '#caa9fa'
    magenta: '#ff79c6'
    cyan:    '#8be9fd'
    white:   '#bfbfbf'

  # Bright colors
  bright:
    black:   '#575b70'
    red:     '#ff6e67'
    green:   '#5af78e'
    yellow:  '#f4f99d'
    blue:    '#caa9fa'
    magenta: '#ff92d0'
    cyan:    '#9aedfe'
    white:   '#e6e6e6'

