#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3.5
bspc config window_gap			 10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle		 true
bspc config focused_border_color "#707070"

bspc rule -a lx-music-desktop	desktop='^9'  follow=on 
bspc rule -a qv2ray				desktop='^10' follow=on
bspc rule -a rofi				focus=on


